export const ALL_DOGS='ALL_DOGS';
export const GET_BY_NAME ='GET_BY_NAME';
export const GET_DETAIL ='GET_DETAIL';
export const PAGE_CLEANER = 'PAGE_CLEANER';
export const GET_TEMPERAMENTS='GET_TEMPERAMENTS';
export const FILTER_BY_TEMPERAMENTS='FILTER_BY_TEMPERAMENTS';
