export const ALL_DOGS='ALL_DOGS';
export const GET_BY_NAME ='GET_BY_NAME';
export const PAGE_CLEANER = 'PAGE_CLEANER';
export const CLEAR_SEARCH ='CLEAR_SEARCH';
export const GET_TEMPERAMENTS='GET_TEMPERAMENTS';
export const FILTERS_BY_TEMPERAMENTS='FILTERS_BY_TEMPERAMENTS';
export const FILTERS_BY_ORIGIN='FILTERS_BY_ORIGIN';
export const ORDER_BY='ORDER_BY';



